name: server_smc
description: Servidor SMC.
version: 1.0.0
# homepage: https://www.localhost.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  dotenv: ^3.0.0
  shelf_static: ^1.1.0
  intl: ^0.17.0 
  date_format: ^2.0.7
  jaguar_jwt: ^3.0.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  mailer: ^5.2.0
  hasura_connect: ^4.0.0+4
  http: ^0.13.4
  encrypt: ^5.0.1
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
  build_runner: ^2.1.4
  shelf_router_generator: ^1.0.1
  injectable_generator: ^1.5.4
